"""Added difficulty to QuizQuestion table

Revision ID: d0800ef8a6f2
Revises: d88d2f239be5
Create Date: 2026-08-13 16:40:25.975118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd0800ef8a6f2'
down_revision: Union[str, Sequence[str], None] = 'd88d2f239be5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_question', sa.Column('difficulty', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_question', 'difficulty')
    # ### end Alembic commands ###
