"""baseline existing schema

Revision ID: d88d2f239be5
Revises: 
Create Date: 2026-08-13 16:04:28.605934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd88d2f239be5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('med_card', 'rxcui',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='RxNorm concept id. Stable join key to RxNorm / DailyMed / openFDA.',
               existing_nullable=True)
    op.alter_column('med_card', 'external_verified_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When last checked against an authoritative source. NULL = AI-generated, UNVERIFIED. Never default this.',
               existing_nullable=True)
    op.drop_index(op.f('idx_med_card_rxcui'), table_name='med_card')
    op.drop_index(op.f('idx_med_card_study_item_id'), table_name='med_card')
    op.drop_constraint(op.f('med_card_study_item_id_key'), 'med_card', type_='unique')
    op.create_index(op.f('ix_med_card_rxcui'), 'med_card', ['rxcui'], unique=False)
    op.create_index(op.f('ix_med_card_study_item_id'), 'med_card', ['study_item_id'], unique=True)
    op.drop_table_comment(
        'med_card',
        existing_comment='Medication card belonging to a study_item of type=med_card.',
        schema=None
    )
    op.alter_column('quiz_question', 'position',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Render order. SQL tables are unordered sets - without this, question order is undefined.',
               existing_nullable=False)
    op.drop_index(op.f('idx_quiz_question_study_item_id'), table_name='quiz_question')
    op.create_index(op.f('ix_quiz_question_study_item_id'), 'quiz_question', ['study_item_id'], unique=False)
    op.drop_table_comment(
        'quiz_question',
        existing_comment='Q&A rows belonging to a study_item of type=quiz.',
        schema=None
    )
    op.alter_column('study_item', 'user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Nullable until auth exists. No default - an unowned row must be NULL, not a random UUID.',
               existing_nullable=True)
    op.alter_column('study_item', 'type',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Discriminator: quiz | med_card',
               existing_nullable=False)
    op.alter_column('study_item', 'source_type',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Provenance: ai_generated | user_typed | external_api',
               existing_nullable=False,
               existing_server_default=sa.text("'ai_generated'::text"))
    op.drop_table_comment(
        'study_item',
        existing_comment='Root table. One row per study artifact; `type` selects the child table.',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'study_item',
        'Root table. One row per study artifact; `type` selects the child table.',
        existing_comment=None,
        schema=None
    )
    op.alter_column('study_item', 'source_type',
               existing_type=sa.TEXT(),
               comment='Provenance: ai_generated | user_typed | external_api',
               existing_nullable=False,
               existing_server_default=sa.text("'ai_generated'::text"))
    op.alter_column('study_item', 'type',
               existing_type=sa.TEXT(),
               comment='Discriminator: quiz | med_card',
               existing_nullable=False)
    op.alter_column('study_item', 'user_id',
               existing_type=sa.UUID(),
               comment='Nullable until auth exists. No default - an unowned row must be NULL, not a random UUID.',
               existing_nullable=True)
    op.create_table_comment(
        'quiz_question',
        'Q&A rows belonging to a study_item of type=quiz.',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_quiz_question_study_item_id'), table_name='quiz_question')
    op.create_index(op.f('idx_quiz_question_study_item_id'), 'quiz_question', ['study_item_id'], unique=False)
    op.alter_column('quiz_question', 'position',
               existing_type=sa.INTEGER(),
               comment='Render order. SQL tables are unordered sets - without this, question order is undefined.',
               existing_nullable=False)
    op.create_table_comment(
        'med_card',
        'Medication card belonging to a study_item of type=med_card.',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_med_card_study_item_id'), table_name='med_card')
    op.drop_index(op.f('ix_med_card_rxcui'), table_name='med_card')
    op.create_unique_constraint(op.f('med_card_study_item_id_key'), 'med_card', ['study_item_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_med_card_study_item_id'), 'med_card', ['study_item_id'], unique=False)
    op.create_index(op.f('idx_med_card_rxcui'), 'med_card', ['rxcui'], unique=False)
    op.alter_column('med_card', 'external_verified_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When last checked against an authoritative source. NULL = AI-generated, UNVERIFIED. Never default this.',
               existing_nullable=True)
    op.alter_column('med_card', 'rxcui',
               existing_type=sa.TEXT(),
               comment='RxNorm concept id. Stable join key to RxNorm / DailyMed / openFDA.',
               existing_nullable=True)
    # ### end Alembic commands ###
